//! gRPC integration through the upstream Tonic runtime.
//!
//! Provides re-exports, channel management, and service registration helpers
//! for integrating gRPC services with Ironic's DI container.

/// The upstream Tonic API used for generated services, clients, status, and transport.
pub use ::tonic as driver;

use crate::{Dependency, ProviderDefinition, Scope};

/// Creates a provider definition for a reusable Tonic channel.
///
/// # Examples
///
/// ```ignore
/// use ironic::distributed::grpc::channel_provider;
/// use tonic::transport::Channel;
///
/// let provider = channel_provider(
///     Channel::from_static("http://localhost:50051")
/// );
/// ```
#[must_use]
pub fn channel_provider(channel: driver::transport::Channel) -> ProviderDefinition {
    ProviderDefinition::value(channel)
}

/// Creates a provider definition for a Tonic service client that depends
/// on a `Channel` registered in the container.
///
/// The service is registered as a transient, so each injection gets a fresh client.
///
/// # Examples
///
/// ```ignore
/// use ironic::distributed::grpc::service_provider;
///
/// // Where GreeterClient<Channel> is generated by tonic-build
/// let provider = service_provider::<GreeterClient<Channel>>();
/// ```
#[must_use]
pub fn service_provider<T>() -> ProviderDefinition
where
    T: Send + Sync + 'static,
    T: From<driver::transport::Channel>,
{
    ProviderDefinition::factory(
        Scope::Singleton,
        vec![Dependency::required::<driver::transport::Channel>()],
        |resolver| async move {
            let channel = resolver.resolve::<driver::transport::Channel>().await?;
            let service = T::from((*channel).clone());
            Ok(service)
        },
    )
}

/// A marker type for registering a gRPC service.
///
/// Use this to declare a gRPC service dependency in your module.
/// The service type should be a tonic-generated service implementation.
pub struct GrpcService<T>(std::marker::PhantomData<T>);

impl<T> GrpcService<T> {
    /// Creates a new gRPC service registration.
    #[must_use]
    pub const fn new() -> Self {
        Self(std::marker::PhantomData)
    }
}

impl<T> Default for GrpcService<T> {
    fn default() -> Self {
        Self(std::marker::PhantomData)
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn tonic_driver_re_exports() {
        let _ = super::driver::Code::Ok;
        let _ = super::driver::Status::new(super::driver::Code::Ok, "test");
    }

    #[test]
    fn channel_provider_type_check() {
        fn _assert(_c: tonic::transport::Channel) {}
    }

    #[test]
    fn grpc_service_type_is_constructible() {
        let _service: super::GrpcService<()> = super::GrpcService::new();
    }
}
